export interface Product {
  name: string;
  desc: string;
  tag: string | null;
  url: string;
  image: string;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  seeAllUrl: string;
  products: Product[];
}

export const categories: Category[] = [
  {
    id: "pole-decorations",
    name: "Light Pole Decorations",
    description:
      "Durable, weather-rated pole-mount displays built to survive Canadian winters. Available in single- and double-sided configurations.",
    seeAllUrl: "/gallery?category=pole-decorations",
    products: [
      {
        name: "Shooting Star Spiral Pole Motif",
        desc: "Warm gold LED spiral ribbon paired with cool white shooting stars and star bursts on a slim vertical frame. Mounts directly to lamp poles for a bright, elegant streetscape accent. Model MF5735-2DC, 200 x 65 cm.",
        tag: null,
        url: "#",
        image: "/ShootingStarSpiralPole.webp",
      },
      {
        name: "Double Star Chasing Pole Motif",
        desc: "Warm gold LED curved ribbon accents framing a sparkling double cool-white star burst, with a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5736-2DC, 200 x 43 cm.",
        tag: null,
        url: "#",
        image: "/DoubleStarChasingPole.webp",
      },
      {
        name: "Twin Star Teardrop Pole Motif",
        desc: "Sparkling cool-white double star cluster set above a warm gold pixel-fill teardrop, framed by a curved cool-white outline, with a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5737-2DC, 200 x 60 cm.",
        tag: null,
        url: "#",
        image: "/TwinStarTeardropPole.webp",
      },
      {
        name: "Multi-Star Cluster Pole Motif",
        desc: "A cascading cluster of warm gold and cool white stars in varied sizes, woven together with swirling cool-white ribbon accents and a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5738-2DC, 200 x 78 cm.",
        tag: null,
        url: "#",
        image: "/MultiStarClusterPole.webp",
      },
      {
        name: "Starwave Street Crossover Motif",
        desc: "Wide horizontal street-crossing motif with interweaving warm gold and cool white ribbon waves flanked by six-point stars. Spans between opposing lamp poles to create a lit archway over roadways and pedestrian streets. Model MF5739-2DH, 400 x 65 cm.",
        tag: null,
        url: "#",
        image: "/StarwaveStreetCrossoverMotif.webp",
      },
      {
        name: "Grand Starwave Arch Motif",
        desc: "Extra-wide horizontal street-crossing motif featuring alternating shooting-star crescents, six-point stars, and a large compound star centrepiece in warm gold and cool white. Spans between opposing lamp poles with a sequential chasing-light effect for added motion. Model MF5740-2DH, 430 x 43 cm.",
        tag: null,
        url: "#",
        image: "/GrandStarwaveArchMotif.webp",
      },
      {
        name: "Galaxy Starwave Arch Motif",
        desc: "Extra-wide horizontal street-crossing motif with a dense field of warm gold and cool white stars in varied sizes, woven together by interlacing ribbon waves and anchored by a large compound star centrepiece. Spans between opposing lamp poles with a sequential chasing-light effect for added motion. Model MF5741-2DH, 715 x 85 cm.",
        tag: "Featured",
        url: "#",
        image: "/GalaxyStarwaveArchMotif.webp",
      },
      {
        name: "Snowflake Scroll Pole Motif",
        desc: "Cool white LED snowflake set above a warm gold pixel-fill scroll ribbon with sparkling cool-white star accents. Slim vertical frame mounts directly to lamp poles for a classic winter streetscape look. Model MF5771-2DC, 200 x 55 cm.",
        tag: null,
        url: "#",
        image: "/SnowflakeScrollPole.webp",
      },
      {
        name: "Triple Snowflake Helix Pole Motif",
        desc: "Three cool white LED snowflakes cascading down a curved warm gold pixel-fill helix ribbon. Slim vertical frame mounts directly to lamp poles for a classic winter streetscape look. Model MF5772-2DC, 200 x 72 cm.",
        tag: null,
        url: "#",
        image: "/TripleSnowflakeHelixPole.webp",
      },
      {
        name: "Gold Star Snowflake Curtain Pole Motif",
        desc: "Warm gold LED pixel-fill curtain panels with scattered star accents, centred on a large cool white and gold LED snowflake burst, with a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5773-2DC, 200 x 75 cm.",
        tag: null,
        url: "#",
        image: "/GoldStarSnowflakeCurtainPole.webp",
      },
      {
        name: "Scroll Snowflake Crossover Motif",
        desc: "Warm gold LED scroll ribbons flanking a single large cool white LED snowflake centrepiece. Wide horizontal frame spans between opposing lamp poles for an elegant street-crossing display. Model MF5775-2DH, 335 x 61 cm.",
        tag: null,
        url: "#",
        image: "/ScrollSnowflakeCrossoverPole.webp",
      },
      {
        name: "Double Helix Snowflake Crossover Motif",
        desc: "Four cool white LED snowflakes woven between interlacing warm gold pixel-fill helix ribbons. Wide horizontal frame spans between opposing lamp poles for a striking winter street-crossing display. Model MF5776-2DH, 400 x 72 cm.",
        tag: null,
        url: "#",
        image: "/DoubleHelixSnowflakeCrossoverPole.webp",
      },
      {
        name: "Snowflake Garland Crossover Motif",
        desc: "Warm gold LED pixel-fill curtain top hung with cascading cool-white garland strands and cool white LED snowflakes of varied sizes, with a sequential chasing-light effect for added motion. Wide horizontal frame spans between opposing lamp poles. Model MF5777-2DH, 500 x 96 cm.",
        tag: "Featured",
        url: "#",
        image: "/SnowflakeGarlandCrossoverPole.webp",
      },
      {
        name: "Flower Medallion Pole Motif",
        desc: "Warm gold and cool white LED flower medallion with a layered petal design in a compact round frame. Mounts directly to lamp poles for a clean, classic accent. Model MF5802-2DH, 60 x 60 cm.",
        tag: null,
        url: "#",
        image: "/FlowerMedallionPole.webp",
      },
      {
        name: "Layered Flower Medallion Pole Motif",
        desc: "Warm gold and cool white LED flower medallion with a fuller layered petal design in a round frame. Mounts directly to lamp poles for a classic streetscape accent. Model MF5803-2DH, 70 x 70 cm.",
        tag: null,
        url: "#",
        image: "/LayeredFlowerMedallionPole.webp",
      },
      {
        name: "Grand Flower Medallion Pole Motif",
        desc: "Large, ornate warm gold and cool white LED flower medallion with a dense sparkling centre burst. Statement-sized round frame mounts directly to lamp poles. Model MF5804-2DH, 90 x 90 cm.",
        tag: null,
        url: "#",
        image: "/GrandFlowerMedallionPole.webp",
      },
      {
        name: "Petite Flower Medallion Pole Motif",
        desc: "Warm gold and cool white LED flower medallion with a layered petal design in a slightly narrower round frame. Mounts directly to lamp poles for a classic streetscape accent. Model MF5805-2DH, 70 x 61 cm.",
        tag: null,
        url: "#",
        image: "/PetiteFlowerMedallionPole.webp",
      },
      {
        name: "Compact Flower Medallion Pole Motif",
        desc: "Warm gold and cool white LED flower medallion with a layered petal design in a compact round frame. Mounts directly to lamp poles for a classic streetscape accent. Model MF5806-2DH, 60 x 52 cm.",
        tag: null,
        url: "#",
        image: "/CompactFlowerMedallionPole.webp",
      },
      {
        name: "Double Flower Scroll Pole Motif",
        desc: "Two warm gold and cool white LED flower medallions linked by a cool white scroll ribbon. Slim vertical frame mounts directly to lamp poles for a classic streetscape display. Model MF5807-2DC, 200 x 70 cm.",
        tag: null,
        url: "#",
        image: "/DoubleFlowerScrollPole.webp",
      },
      {
        name: "Flower & Leaf Pole Motif",
        desc: "Warm gold and cool white LED flower medallion paired with a warm gold pixel-fill leaf below, framed by a cool white curved outline. Slim vertical frame mounts directly to lamp poles. Model MF5808-2DC, 200 x 62 cm.",
        tag: null,
        url: "#",
        image: "/FlowerLeafPole.webp",
      },
      {
        name: "Circular Flower Leaf Pole Motif",
        desc: "Cool white LED circular flower medallion paired with a curved warm gold pixel-fill leaf panel, with a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5809-2DC, 200 x 62 cm.",
        tag: null,
        url: "#",
        image: "/CircularFlowerLeafPole.webp",
      },
      {
        name: "Circular Flower Scroll Pole Motif",
        desc: "Cool white LED circular flower medallion paired with a double cool-white scroll over a warm gold pixel-fill panel, with a sequential chasing-light effect for added motion. Slim vertical frame mounts directly to lamp poles. Model MF5810-2DC, 200 x 70 cm.",
        tag: null,
        url: "#",
        image: "/CircularFlowerScrollPole.webp",
      },
      {
        name: "Flower Wing Crossover Motif",
        desc: "Warm gold and cool white LED flower medallion centred between two sweeping warm gold pixel-fill wing scrolls with cool white curled tips. Spans between opposing lamp poles for an elegant street-crossing display. Model MF5811-2DH, 313 x 76 cm.",
        tag: null,
        url: "#",
        image: "/FlowerWingCrossoverPole.webp",
      },
      {
        name: "Triple Flower Scroll Crossover Motif",
        desc: "Three warm gold and cool white LED flower medallions linked by cool white scroll ribbons. Wide horizontal frame spans between opposing lamp poles for a classic street-crossing display. Model MF5812-2DH, 330 x 70 cm.",
        tag: null,
        url: "#",
        image: "/TripleFlowerScrollCrossoverPole.webp",
      },
      {
        name: "Flower Medallion Crossover Motif",
        desc: "Warm gold and cool white LED flower medallion centred between two circular flower medallions, linked by cool white scroll ribbons over a warm gold pixel-fill curtain, with a sequential chasing-light effect for added motion. Spans between opposing lamp poles. Model MF5813-2DH, 400 x 90 cm.",
        tag: "Featured",
        url: "#",
        image: "/FlowerMedallionCrossoverPole.webp",
      },
      {
        name: "Flower Wave Crossover Motif",
        desc: "Three warm gold and cool white LED flower medallions set within a sweeping crescent of warm gold pixel-fill, with a sequential chasing-light effect for added motion. Wide horizontal frame spans between opposing lamp poles. Model MF5814-2DH, 500 x 75 cm.",
        tag: null,
        url: "#",
        image: "/FlowerWaveCrossoverPole.webp",
      },
      {
        name: "Bauble & Bow Pole Motif",
        desc: "Warm gold and cool blue LED ornament bauble pair with a sparkling red LED bow topper. Mounts directly to lamp poles for a festive, high-visibility civic accent. Model MF5826-2DH, 105 x 100 cm.",
        tag: null,
        url: "#",
        image: "/BaubleBowPole.webp",
      },
      {
        name: "Spiral Tree Pole Motif",
        desc: "Green and warm gold LED spiral Christmas tree with a star topper and accent stars. Mounts directly to lamp poles for a festive, high-visibility civic accent. Model MF5827-2DH, 130 x 100 cm.",
        tag: null,
        url: "#",
        image: "/SpiralTreePole.webp",
      },
      {
        name: "Gift Boxes Pole Motif",
        desc: "Warm gold LED gift boxes with cool blue and red ribbon accents and sparkling star flourishes. Mounts directly to lamp poles for a festive, high-visibility civic accent. Model MF5828-2DH, 130 x 90 cm.",
        tag: null,
        url: "#",
        image: "/GiftBoxesPole.webp",
      },
      {
        name: "Spiral Tree Panel Pole Motif",
        desc: "Green and warm gold LED spiral Christmas tree with a star topper and accent stars, framed in a slim vertical panel. Mounts directly to lamp poles. Model MF5829-2DC, 200 x 90 cm.",
        tag: null,
        url: "#",
        image: "/SpiralTreeFramedPole.webp",
      },
      {
        name: "Classic Tree Panel Pole Motif",
        desc: "Solid green LED Christmas tree silhouette with a red star topper, framed in a slim vertical panel. Mounts directly to lamp poles for a classic seasonal look. Model MF5830-2DC, 200 x 70 cm.",
        tag: null,
        url: "#",
        image: "/ClassicTreePole.webp",
      },
      {
        name: "Triple Ornament Ribbon Pole Motif",
        desc: "Three warm gold, cool blue, and violet LED ornament baubles linked by a sparkling red LED ribbon, framed in a slim vertical panel. Mounts directly to lamp poles. Model MF5831-2DC, 200 x 70 cm.",
        tag: null,
        url: "#",
        image: "/TripleOrnamentRibbonPole.webp",
      },
      {
        name: "Gift Box Ribbon Pole Motif",
        desc: "Warm gold and cool blue LED gift box with a flowing red LED ribbon and sparkling star accents, framed in a slim vertical panel. Mounts directly to lamp poles. Model MF5832-2DC, 200 x 80 cm.",
        tag: "Featured",
        url: "#",
        image: "/GiftBoxRibbonPole.webp",
      },
      {
        name: "Sunburst Ring Pole Motif",
        desc: "Warm gold LED sunburst ring with alternating diamond-point rays. Mounts around existing street lamp heads for a striking civic display. Model MF5836-2DC, 120 x 108 cm.",
        tag: null,
        url: "#",
        image: "/SunburstRingPole.webp",
      },
      {
        name: "Snowflake Ring Pole Motif",
        desc: "Cool white LED ring made of repeating snowflake motifs. Mounts around existing street lamp heads for a bright winter civic display. Model MF5837-2DC, 120 x 112 cm.",
        tag: "Featured",
        url: "#",
        image: "/SnowflakeRingPole.webp",
      },
      {
        name: "Ornate Scroll Ring Pole Motif",
        desc: "Warm gold LED ring featuring intricate scrollwork and diamond-point accents. Mounts around existing street lamp heads for a striking civic display. Model MF5838-2DC, 130 x 113 cm.",
        tag: null,
        url: "#",
        image: "/OrnateScrollRingPole.webp",
      },
      {
        name: "Star & Leaf Ring Pole Motif",
        desc: "Warm gold LED ring featuring a crown of stars paired with sparkling leaf-drop accents, with a sequential chasing-light effect for added motion. Mounts around existing street lamp heads. Model MF5839-2DC, 120 x 115 cm.",
        tag: null,
        url: "#",
        image: "/StarLeafRingPole.webp",
      },
      {
        name: "Star Ring Pole Motif",
        desc: "LED ring featuring stars evenly spaced around the full circle. Mounts around existing street lamp heads for a twinkling civic display. Model MF5840-2DC, 118 x 106 cm.",
        tag: null,
        url: "#",
        image: "/StarRingPole.webp",
      },
      {
        name: "Scroll & Star Ring Pole Motif",
        desc: "Cool white LED ring featuring scrollwork curls at the base and sparkling star accents at the top. Mounts around existing street lamp heads for an elegant civic display. Model MF5841-2DC, 115 x 107 cm.",
        tag: null,
        url: "#",
        image: "/ScrollStarRingPole.webp",
      },
      {
        name: "Crown Scroll Pole Motif",
        desc: "Warm gold LED scrollwork cluster arching over the lamp head with sparkling star accents at the sides. Mounts around existing street lamp heads for a striking civic display. Model MF5842-2DC, 130 x 100 cm.",
        tag: null,
        url: "#",
        image: "/CrownScrollPole.webp",
      },
      {
        name: "Orbit Star Ring Pole Motif",
        desc: "Cool white LED orbiting rings with scattered star accents encircling the lamp head. Mounts around existing street lamp heads for a dynamic civic display. Model MF5843-2DC, 125 x 110 cm.",
        tag: null,
        url: "#",
        image: "/OrbitStarRingPole.webp",
      },
      {
        name: "Teardrop Star Pole Motif",
        desc: "Warm gold LED pixel-fill teardrop ribbon topped with two sparkling cool white stars. Mounts around existing street lamp heads for an elegant civic display. Model MF5844-2DC, 124 x 105 cm.",
        tag: null,
        url: "#",
        image: "/TeardropStarPole.webp",
      },
      {
        name: "Crescent Moon & Star Pole Motif",
        desc: "Warm gold LED pixel-fill crescent moon paired with sparkling cool white star accents. Mounts around existing street lamp heads for a striking civic display. Model MF5845-2DC, 125 x 103 cm.",
        tag: null,
        url: "#",
        image: "/CrescentMoonStarPole.webp",
      },
      {
        name: "Swan Wing Pole Motif",
        desc: "Cool white LED curved wing outlines with cool blue pixel-fill accents. Mounts directly to lamp poles for a striking civic display. Model MF5846-2DC, 105 x 35 cm (one side).",
        tag: null,
        url: "#",
        image: "/SwanWingBluePole.webp",
      },
      {
        name: "Angular Wing Pole Motif",
        desc: "Cool white LED angular wing outlines with matching pixel-fill panels. Mounts directly to lamp poles for a clean, modern civic display. Model MF5847-2DC, 80 x 42 cm (one side).",
        tag: null,
        url: "#",
        image: "/AngularWingPole.webp",
      },
      {
        name: "Scroll Wing Pole Motif",
        desc: "Cool white LED curled scroll wing outlines with warm gold pixel-fill accents. Mounts directly to lamp poles for an elegant civic display. Model MF5848-2DC, 80 x 35 cm (one side).",
        tag: null,
        url: "#",
        image: "/ScrollWingPole.webp",
      },
      {
        name: "Star Wing Pole Motif",
        desc: "Cool white LED wing outlines topped with sparkling stars and filled with cool blue pixel accents, with a sequential chasing-light effect for added motion. Mounts directly to lamp poles. Model MF5849-2DC, 85 x 47 cm (one side).",
        tag: "Featured",
        url: "#",
        image: "/StarWingBluePole.webp",
      },
      {
        name: "White Snowflake Pole Motif",
        desc: "Cool white LED snowflake with a clean, all-white outline. Compact size mounts directly to lamp poles or storefronts for a crisp winter accent. Model MF5766-2DH, 60 x 55 cm.",
        tag: null,
        url: "#",
        image: "/WhiteSnowflakePoleA.webp",
      },
      {
        name: "Gold-Accent Snowflake Pole Motif",
        desc: "Cool white LED snowflake outline with warm gold pixel-fill accents along the branches. Mounts directly to lamp poles or storefronts for a warm winter accent. Model MF5767-2DH, 70 x 61 cm.",
        tag: null,
        url: "#",
        image: "/BoldGoldSnowflakePole.webp",
      },
      {
        name: "Gold-Fill Snowflake Pole Motif",
        desc: "Cool white LED snowflake outline with warm gold pixel-fill diamond sections and a gold star centre. Larger size mounts directly to lamp poles or storefronts for a striking winter accent. Model MF5768-2DH, 80 x 70 cm.",
        tag: null,
        url: "#",
        image: "/WhiteGoldSnowflakePole.webp",
      },
      {
        name: "Golden Snowflake Pole Motif",
        desc: "Warm gold LED snowflake with cool white outline accents along the branch tips. Mounts directly to lamp poles or storefronts for a warm winter accent. Model MF5769-2DH, 70 x 61 cm.",
        tag: null,
        url: "#",
        image: "/GoldSnowflakePole.webp",
      },
      {
        name: "Classic White Snowflake Pole Motif",
        desc: "Cool white LED snowflake with a clean, all-white outline. Compact size mounts directly to lamp poles or storefronts for a crisp winter accent. Model MF5770-2DH, 60 x 54 cm.",
        tag: null,
        url: "#",
        image: "/WhiteSnowflakePoleB.webp",
      },
    ],
  },
  {
    id: "string-lights",
    name: "String Lights & RGB",
    description:
      "Commercial-grade string lights engineered for heavy seasonal use. Full RGB colour control available across the entire range.",
    seeAllUrl: "/gallery?category=string-lights",
    products: [
      {
        name: "RNL2C Rubber Wire String Light with Concave Cap",
        desc: "Warm white rubber-wire string light with frosted concave cap bulbs. Flexible, durable, and rated for outdoor winter use.",
        tag: null,
        url: "#",
        image: "/RNL2Cconcave.webp",
      },
      {
        name: "RGL2C Rubber Wire String Light with Bullet Cap",
        desc: "Cool white rubber-wire string light with bullet cap bulbs. Clean, crisp output ideal for modern commercial displays. Outdoor-rated.",
        tag: null,
        url: "#",
        image: "/RNL2Cbulletcap.webp",
      },
      {
        name: "RGL2C PVC Wire String Light Mini Concave Cap",
        desc: "Warm white PVC wire string light with mini concave cap bulbs. Compact profile, rich amber glow, ideal for dense decorative installations.",
        tag: null,
        url: "#",
        image: "/RGL2C.webp",
      },
      {
        name: "String Light with Flash LED",
        desc: "High-intensity cool white flash LED string light on clear wire. Brilliant starburst effect ideal for high-visibility commercial and municipal displays.",
        tag: null,
        url: "#",
        image: "/FlashLed.webp",
      },
      {
        name: "36V String Light",
        desc: "Warm white 36V low-voltage string light with elongated bullet cap bulbs. Power supply available. Safe, energy-efficient, and ideal for large-scale municipal installations.",
        tag: null,
        url: "#",
        image: "/36V.webp",
      },
      {
        name: "24V String Light",
        desc: "Cool white 24V low-voltage string light on clear wire with mini bullet cap bulbs. Power supply available. Linkable and safe for extended commercial runs.",
        tag: null,
        url: "#",
        image: "/24V.webp",
      },
      {
        name: "SGL2C PVC Wire String Light",
        desc: "Warm white PVC wire string light with end-to-end connection. Easily daisy-chain multiple runs for seamless coverage across large municipal and commercial installations.",
        tag: null,
        url: "#",
        image: "/SGL2C.webp",
      },
      {
        name: "SL2C/CSL2C PVC Wire String Light",
        desc: "Warm white PVC wire string light with large dome cap bulbs on dark green wire. Bold, classic profile suited for tree wrapping, garlands, and commercial seasonal displays.",
        tag: null,
        url: "#",
        image: "/CLS2C.webp",
      },
      {
        name: "RL2C PVC Wire Shrinkable String Light",
        desc: "Cool white indoor PVC wire string light with shrinkable cap bulbs on black wire. Designed for interior seasonal décor, retail displays, and covered venue installations.",
        tag: null,
        url: "#",
        image: "/RL2Cwhite.webp",
      },
      {
        name: "RL2C PVC Wire Shrinkable String Light — Multicolor",
        desc: "Multicolor indoor PVC wire string light with shrinkable cap bulbs on black wire. Vibrant mix of red, blue, green, orange, and white. For interior seasonal décor and retail displays.",
        tag: null,
        url: "#",
        image: "/RL2Cmulti.webp",
      },
      {
        name: "Ultra Bright String Light",
        desc: "High-output warm white string light on white wire with frosted bullet cap bulbs. Exceptional brightness for tree wrapping, rooflines, and high-visibility seasonal displays.",
        tag: null,
        url: "#",
        image: "/UltraBright.webp",
      },
      {
        name: "CNL2C Curtain Light",
        desc: "Warm white curtain light with cascading vertical strands on black wire. Ideal for building facades, window displays, and large-surface seasonal installations.",
        tag: null,
        url: "#",
        image: "/CNL2C.webp",
      },
      {
        name: "Dual Color String Light",
        desc: "Switchable dual color string light — cool white on one side, warm white on the other. One installation, two seasonal looks. Perfect for versatile commercial and municipal displays.",
        tag: null,
        url: "#",
        image: "/DualColor.webp",
      },
      {
        name: "INL2C Icicle Light",
        desc: "Warm white icicle light with variable-length draping strands on black wire. Creates a classic roofline icicle effect for eaves, awnings, and building edges.",
        tag: null,
        url: "#",
        image: "/INL2C.webp",
      },
      {
        name: "LED Snowfall 23mm",
        desc: "Cool white 23mm acrylic snowfall tubes with a cascading meteor-shower chase effect that mimics falling snow. Tapered tips and clear tubing on black wire, with multiple linkable tubes per set. Ideal for rooflines, eaves, and tree-mounted seasonal displays.",
        tag: null,
        url: "#",
        image: "/SnowfallTube23mm.webp",
      },
      {
        name: "LED Snowfall 30mm",
        desc: "Cool white 30mm acrylic snowfall tube with the same cascading meteor-shower chase effect that mimics falling snow, in a larger diameter for higher output and visibility. Rigid clear tubing with daisy-chain connectors on both ends for linking multiple units. Ideal for rooflines, eaves, and tree-mounted seasonal displays.",
        tag: null,
        url: "#",
        image: "/SnowfallTube30mm.webp",
      },
      {
        name: "Mini Meteor Light",
        desc: "Multicolor mini meteor tubes in green, blue, purple, red, amber, and white with a cascading chase effect that mimics shooting meteors. Slim compact profile, linkable for extended runs. Ideal for tree wrapping, garden borders, and vibrant seasonal displays.",
        tag: "Featured",
        url: "#",
        image: "/MiniMeteorLight.webp",
      },
      {
        name: "LED Cracker Light",
        desc: "Warm white LED cracker light on white wire with elongated frosted cap bulbs. Bright, even glow ideal for garlands, tree wrapping, and indoor seasonal displays.",
        tag: null,
        url: "#",
        image: "/CrackerLight.webp",
      },
      {
        name: "NNL2C Net Light",
        desc: "Warm white LED net light with vertical and horizontal connection options. Drape over hedges, wrap ground cover, or mount on flat surfaces for seamless large-area coverage.",
        tag: null,
        url: "#",
        image: "/NNL2C.webp",
      },
      {
        name: "LED String Light with Multi Star — Double Stars Cap",
        desc: "Warm white string light on white wire with faceted double-star cap bulbs. The multi-surface cut creates a brilliant prismatic sparkle effect for premium seasonal displays.",
        tag: null,
        url: "#",
        image: "/MultiStar.webp",
      },
      {
        name: "String Light with Waterfall Effect",
        desc: "Green RGB string light on green wire with a flowing waterfall chase sequence. Produces a cascading colour effect ideal for tree installations and large outdoor seasonal displays.",
        tag: null,
        url: "#",
        image: "/WaterfallEffect.webp",
      },
      {
        name: "RGB Digital String Light — 24V",
        desc: "24V RGB digital string light with custom animation effects and DMX compatibility. Multicolour with multiple selectable effects. PLC 2-wire technology — no complicated wiring. Automated machine production for stable quality and neat appearance.",
        tag: null,
        url: "#",
        image: "/RGBDigital24V.webp",
      },
      {
        name: "RGB Color Changing String Light — Synchronous",
        desc: "Teal-to-multicolour RGB string light with synchronous color changing. Two-wire structure, no complicated wiring. Extends easily across runs. Control effects: slow color change, quick color change, or single-color static. Automated production for reliable quality.",
        tag: null,
        url: "#",
        image: "/RGBSync.webp",
      },
      {
        name: "RGB Twinkle String Light — Sync & App Control",
        desc: "Multicolor RGB twinkle string light on clear wire with app control via smartphone. Two wires only, more functions. Available in multicolor, blue, white, green, red, and warm white. Control effects: slow change, quick change, single-color static. Steady on, twinkle, and multicolor modes.",
        tag: null,
        url: "#",
        image: "/RGBTwinkle.webp",
      },
      {
        name: "RGB Twinkle String Light — Sync & Remote Control",
        desc: "Multicolor RGB twinkle string light with 17-key remote controller. Two wires only. Available in multicolor, blue, white, green, red, and warm white. Control effects: slow change, quick change, single-color static. Steady on, twinkle, and multicolor modes.",
        tag: "Featured",
        url: "#",
        image: "/RGBTwinkleRemote.webp",
      },
      {
        name: "RGB Bullet Pixel Light",
        desc: "Digital RGB bullet pixel light with wide view angle and easy outdoor installation. Each bulb is individually addressable for stunning dynamic effects. Ideal for large-scale commercial and municipal seasonal displays.",
        tag: null,
        url: "#",
        image: "/RGBPixel.webp",
      },
      {
        name: "Bullet Pixel Light",
        desc: "High-brightness white bullet pixel light with wide view angle and easy installation. Individually mounted bulbs deliver powerful, uniform output for large commercial and municipal installations.",
        tag: null,
        url: "#",
        image: "/BulletPixel.webp",
      },
      {
        name: "LED Strobe Bulb",
        desc: "High-intensity individually mounted strobe bulb available in blue, white, and amber. Sharp, brilliant flash output for maximum visibility. Easy installation in bullet-style mounts — ideal for high-impact commercial and municipal seasonal displays.",
        tag: "Featured",
        url: "#",
        image: "/LEDStrobeBulb.webp",
      },
      {
        name: "Super Bright Chain Light",
        desc: "High-brightness cool white chain light with faceted dome bulbs individually mounted on durable white multi-wire cable. Sharp, focused output for maximum visibility. Linkable connectors for extended runs — ideal for large-scale commercial and municipal seasonal installations.",
        tag: null,
        url: "#",
        image: "/SuperBrightChainLight.webp",
      },
      {
        name: "E14 LED Mini Bulb",
        desc: "Multicolor E14 mini LED bulb string with individually mounted red, white, blue, pink, purple, green, and yellow bulbs on durable black wire. Replaceable E14 screw-base sockets and IP65 waterproof construction. Ideal for vibrant decorative and seasonal commercial displays.",
        tag: null,
        url: "#",
        image: "/E14MiniBulb.webp",
      },
      {
        name: "Fairy Light — Solar Operated",
        desc: "Multicolor micro LED fairy lights on ultra-soft copper wire with PVC coating. Solar powered with remote control — all in one. UV glue and eco-friendly PVC. Works for garden, patio, party, Christmas, and home decorations. Bends into any shape.",
        tag: null,
        url: "#",
        image: "/FairyLightSolar.webp",
      },
      {
        name: "Fairy Light — Battery Operated",
        desc: "Multicolor micro LED fairy lights on ultra-soft copper wire with PVC coating. Battery box and controller included — all in one. UV glue and eco-friendly PVC. Perfect for wedding centrepieces, parties, Christmas, Halloween, and table décor. Bends into any shape.",
        tag: null,
        url: "#",
        image: "/FairyLightBattery.webp",
      },
      {
        name: "Fairy Light — With Adapter",
        desc: "Multicolor micro LED fairy lights on ultra-soft copper wire with PVC coating. Adapter and controller included — all in one. UV glue and eco-friendly PVC. Perfect for wedding centrepieces, parties, Christmas, Halloween, and table décor. Bends into any shape.",
        tag: null,
        url: "#",
        image: "/FairyLightAdapter.webp",
      },
      {
        name: "Fairy Light — USB Plug",
        desc: "Warm white micro LED fairy lights on ultra-soft copper wire with PVC coating. USB plug and controller included — all in one. UV glue and eco-friendly PVC. Perfect for wedding centrepieces, parties, Christmas, Halloween, and table décor. Bends into any shape.",
        tag: null,
        url: "#",
        image: "/FairyLightUSB.webp",
      },
      {
        name: "Smart Fairy Light — App Control",
        desc: "Multicolor micro LED fairy lights on copper wire with PVC coating. Ultra-soft for different shapes. Adapter and app control included — all in one. UV glue and eco-friendly PVC. Works for wedding centrepieces, parties, Christmas, Halloween, and table décor.",
        tag: null,
        url: "#",
        image: "/FairyLightApp.webp",
      },
      {
        name: "Pure Fairy Light",
        desc: "Multicolor micro LED fairy lights on ultra-soft copper wire with PVC coating. Compatible with various power sources. UV glue and eco-friendly PVC. Versatile for any application — projects, installations, seasonal displays, and decorative lighting of all kinds.",
        tag: null,
        url: "#",
        image: "/FairyLightPure.webp",
      },
      {
        name: "D Shape Neon Flex Light",
        desc: "Warm white D-profile neon flex light with a smooth continuous glow and no hot spots. Highly flexible silicone housing bends easily around curves and corners. Ideal for architectural outlines, signage, rooflines, and large-scale decorative installations.",
        tag: null,
        url: "#",
        image: "/NeonFlexD.webp",
      },
      {
        name: "360° Neon Rope Light",
        desc: "Amber gold 360° round neon rope light with full circumferential illumination and no directional bias. Flexible silicone tubing for tight bends and custom shapes. Perfect for outlining structures, creating lettering, and high-impact commercial seasonal displays.",
        tag: null,
        url: "#",
        image: "/NeonRope360.webp",
      },
      {
        name: "Single Side Neon Flex Light",
        desc: "Cool white single-sided neon flex light with a flat bottom profile for flush mounting. Waterproof silicone housing with crisp uniform top-emission. Ideal for rooflines, ground-level outlines, architectural coves, and outdoor signage.",
        tag: null,
        url: "#",
        image: "/NeonFlexSingle.webp",
      },
      {
        name: "Ribbon Neon Flex Light",
        desc: "Cool white ultra-flexible ribbon neon flex light with a slim flat profile. Bends freely in any direction for tight curves, lettering, and intricate shapes. Smooth continuous glow with no visible LED points. Ideal for custom signage, architectural accents, and decorative outlines.",
        tag: null,
        url: "#",
        image: "/NeonFlexRibbon.webp",
      },
      {
        name: "SMD-5050 RGB LED Neon Flex — Async",
        desc: "Full-colour SMD-5050 RGB neon flex available in teal, red, amber, warm white, and blue. Asynchronous colour control for independent zone management. Smooth uniform glow with no hot spots. Ideal for vibrant architectural outlines, seasonal signage, and large-scale commercial colour displays.",
        tag: "Featured",
        url: "#",
        image: "/NeonFlexRGBAsync.webp",
      },
      {
        name: "SMD-5050 RGB LED Neon Flex — Sync",
        desc: "Full-colour SMD-5050 RGB neon flex in red, green, and blue with synchronous colour control. All zones change colour simultaneously for bold unified displays. Smooth uniform glow with no hot spots. Perfect for large-scale architectural outlines and coordinated seasonal colour installations.",
        tag: null,
        url: "#",
        image: "/NeonFlexRGBSync.webp",
      },
      {
        name: "LED Flash Rope Light",
        desc: "Cool white LED flash rope light encased in clear flexible PVC tubing. High-output chips produce a bold, crisp flash effect. Waterproof and weatherproof — ideal for rooflines, pathways, perimeter outlines, and high-visibility seasonal commercial displays.",
        tag: null,
        url: "#",
        image: "/FlashRopeLight.webp",
      },
      {
        name: "Mini Rope Light — Copper Wire with SMD",
        desc: "Cool white mini rope light combining a copper wire core with SMD chips for high brightness in an ultra-soft, slim profile. IP65 waterproof clear PVC tubing. Ideal for compact trim work, pathways, and detail accents where a slimmer rope is needed.",
        tag: null,
        url: "#",
        image: "/MiniRopeLightSMD.webp",
      },
      {
        name: "Mini SMD 2835 Rope Light",
        desc: "Warm white mini rope light built on a copper wire core with SMD-2835 chips for a tighter, more efficient beam in an ultra-soft, slim profile. IP65 waterproof clear PVC tubing. Ideal for compact trim work, pathways, and detail accents where a slimmer rope is needed.",
        tag: null,
        url: "#",
        image: "/MiniRopeLight2835.webp",
      },
      {
        name: "2 Wire LED Rope Light",
        desc: "Warm white 2-wire LED rope light encased in clear flexible PVC tubing. Waterproof with individual point-source LEDs for a classic sparkle effect. Ideal for rooflines, pathways, tree wrapping, and large-scale seasonal perimeter lighting.",
        tag: null,
        url: "#",
        image: "/RopeLight2Wire.webp",
      },
      {
        name: "2 Wire LED Rope Light — Project Spool",
        desc: "Warm white and cool white 2-wire LED rope light supplied on large project spools. Available in bulk lengths for major installations. Ideal for municipalities, contractors, and commercial projects requiring continuous runs across large sites.",
        tag: null,
        url: "#",
        image: "/RopeLight2WireProject.webp",
      },
      {
        name: "2 Wire LED Rope Light — Retail",
        desc: "Warm white 2-wire LED rope light in a convenient pre-coiled retail pack with integrated power connector. Ready to install out of the box. Perfect for smaller commercial jobs, retail displays, and event decorating.",
        tag: null,
        url: "#",
        image: "/RopeLight2WireRetail.webp",
      },
      {
        name: "RGB Twinkle Rope Light — Sync & App Control",
        desc: "Multicolor RGB twinkle rope light in clear PVC tubing with smartphone app control. Two wires only, more functions. Steady on, twinkle, and multi-color modes. Control effects: slow color change, quick color change, single color static. Waterproof and linkable for large commercial seasonal displays.",
        tag: "Featured",
        url: "#",
        image: "/RGBTwinkleRope.webp",
      },
      {
        name: "RGB Twinkle Rope Light — Sync & Remote Control",
        desc: "Multicolor RGB twinkle rope light in clear PVC tubing with 17-key remote controller. Two wires only, more functions. Steady on, twinkle, and multi-color modes. Control effects: slow color change, quick color change, single color static. Waterproof and linkable for large commercial seasonal displays.",
        tag: null,
        url: "#",
        image: "/RGBTwinkleRopeSync.webp",
      },
      {
        name: "Silicone Rope Light",
        desc: "Cool white silicone rope light with ultra-soft flexible housing. IP65 waterproof, UV resistant, and rated for high and low temperature extremes. Ideal for permanent and seasonal outdoor installations across Canadian climates.",
        tag: null,
        url: "#",
        image: "/SiliconeRopeLight.webp",
      },
      {
        name: "Candy Cane Rope Light",
        desc: "Warm white LED rope light with a festive red and white candy cane spiral PVC tubing. Ultra-soft, eco-friendly PVC suitable for outdoor use. Available in retail and project spool formats. Instantly recognizable for seasonal streetscapes, retail displays, and holiday events.",
        tag: null,
        url: "#",
        image: "/CandyCaneRope.webp",
      },
      {
        name: "5050 Soft Strip Light",
        desc: "Warm white SMD-5050 soft LED strip light on pure copper wire with copper film layer PTC. Flexible, bendable, unbreakable, and cuttable. Ultra-bright with low light attenuation LEDs and eco-friendly PVC. Ideal for architectural coves, signage, retail displays, and decorative accent lighting.",
        tag: null,
        url: "#",
        image: "/Strip5050.webp",
      },
      {
        name: "UL 5050 Soft Strip Light",
        desc: "Cool white UL-listed SMD-5050 soft LED strip light on pure copper wire with copper film layer PTC. Flexible, bendable, unbreakable, and cuttable. Ultra-bright with low light attenuation LEDs and eco-friendly PVC. Meets North American safety standards for commercial and municipal seasonal installations.",
        tag: null,
        url: "#",
        image: "/Strip5050UL.webp",
      },
      {
        name: "2835 Soft Strip Light",
        desc: "Warm white SMD-2835 soft LED strip light on pure copper wire with copper film layer PTC. Flexible, bendable, unbreakable, and cuttable. Ultra-bright with low light attenuation LEDs and eco-friendly PVC. The 2835 chip delivers higher efficiency and a tighter, more uniform beam than standard 5050.",
        tag: null,
        url: "#",
        image: "/Strip2835.webp",
      },
      {
        name: "ETL 2835 Soft Strip Light",
        desc: "Cool white ETL-certified SMD-2835 soft LED strip light with a dual-row LED layout for extra brightness. Flexible, bendable, unbreakable, and cuttable silicone-jacketed tubing for outdoor use. ETL certification meets North American safety standards for commercial and municipal seasonal installations.",
        tag: null,
        url: "#",
        image: "/Strip2835ETL.webp",
      },
      {
        name: "Digital RGB Soft Strip Light",
        desc: "Full-colour digital RGB soft LED strip light with individually addressable pixels for smooth colour-changing and colour-chasing sequences. Custom animation effects programmable as required. Flexible, cuttable clear PVC tubing on copper wire. Ideal for dynamic architectural, retail, and large-scale seasonal colour displays.",
        tag: null,
        url: "#",
        image: "/RGBDigitalStrip.webp",
      },
      {
        name: "Ultra Soft COB Strip Light",
        desc: "Warm white COB soft LED strip light with high-density chip-on-board LEDs for an ultra-smooth, continuous glow with no visible dots or light shadow. Super slim profile with better colour consistency end-to-end. IP65 waterproof and cuttable at short intervals. Ideal for architectural coves, signage, and premium accent lighting.",
        tag: "Featured",
        url: "#",
        image: "/COBStripLight.webp",
      },
      {
        name: "5050 Wireless Strip Light",
        desc: "Cool white SMD-5050 LED strip light built without any internal copper wire, for high lumen output and high efficiency. Patented waterproof connecting design allows sections to be easily cut, reconnected, and reinstalled without splicing. Ideal for retrofits, repairs, and large-scale installations needing fast field servicing.",
        tag: null,
        url: "#",
        image: "/Strip5050Wireless.webp",
      },
      {
        name: "2835 Wireless Strip Light",
        desc: "Warm white SMD-2835 LED strip light built without any internal copper wire, for high lumen output and high efficiency. Patented waterproof connecting design allows sections to be easily cut, reconnected, and reinstalled without splicing. The 2835 chip delivers a tighter, more uniform beam — ideal for retrofits, repairs, and large-scale installations needing fast field servicing.",
        tag: null,
        url: "#",
        image: "/Strip2835Wireless.webp",
      },
      {
        name: "DL45 COB Bulb",
        desc: "Warm white DL45 globe bulb with a vintage-style COB filament on durable black festoon cable. Clear glass-look globe produces a warm, ambient glow reminiscent of classic Edison bulbs. Linkable connectors for café strings, patio festoons, and decorative commercial seasonal lighting.",
        tag: null,
        url: "#",
        image: "/DL45COBBulb.webp",
      },
      {
        name: "S14 Edison Bulb",
        desc: "Warm white S14 teardrop bulb with an exposed vintage-style LED filament on durable black festoon cable. Classic Edison-bulb silhouette with a soft, ambient glow. Linkable connectors for café strings, patio festoons, and decorative commercial seasonal lighting.",
        tag: null,
        url: "#",
        image: "/S14EdisonBulb.webp",
      },
      {
        name: "C7 / C9 Bulb",
        desc: "Amber warm white C7 and C9 faceted torpedo-shape bulbs with a classic visible LED filament. Traditional incandescent-style silhouette in two standard sizes for replacement or new installs across light pole, rooftop, and large-scale commercial seasonal fixtures.",
        tag: null,
        url: "#",
        image: "/C7C9Bulb.webp",
      },
    ],
  },
  {
    id: "animated-lighting",
    name: "Dancing Lights",
    description:
      "Programmed sequences and motion effects that bring installations to life. From simple twinkle to full DMX show control.",
    seeAllUrl: "/gallery?category=animated-lighting",
    products: [
      {
        name: "Firework Light",
        desc: "Cool white LED firework motif featuring radiating tube spokes that chase outward from a central hub, mimicking an exploding firework burst. Multiple units link together on suspension cable for canopy-style overhead displays. Ideal for plazas, pedestrian streets, and large-scale festive seasonal installations.",
        tag: "New",
        url: "#",
        image: "/FireworkLight.webp",
      },
      {
        name: "RGB Twinkle String Light — Sync & App Control",
        desc: "Multicolor RGB twinkle string light on clear wire with app control via smartphone. Two wires only, more functions. Available in multicolor, blue, white, green, red, and warm white. Control effects: slow change, quick change, single-color static. Steady on, twinkle, and multicolor modes.",
        tag: "New",
        url: "#",
        image: "/RGBTwinkle.webp",
      },
      {
        name: "RGB Twinkle String Light — Sync & Remote Control",
        desc: "Multicolor RGB twinkle string light with 17-key remote controller. Two wires only. Available in multicolor, blue, white, green, red, and warm white. Control effects: slow change, quick change, single-color static. Steady on, twinkle, and multicolor modes.",
        tag: "New",
        url: "#",
        image: "/RGBTwinkleRemote.webp",
      },
      {
        name: "RGB Twinkle Rope Light — Sync & App Control",
        desc: "Multicolor RGB twinkle rope light in clear PVC tubing with smartphone app control. Two wires only, more functions. Steady on, twinkle, and multi-color modes. Control effects: slow color change, quick color change, single color static. Waterproof and linkable for large commercial seasonal displays.",
        tag: "New",
        url: "#",
        image: "/RGBTwinkleRope.webp",
      },
      {
        name: "RGB Twinkle Rope Light — Sync & Remote Control",
        desc: "Multicolor RGB twinkle rope light in clear PVC tubing with 17-key remote controller. Two wires only, more functions. Steady on, twinkle, and multi-color modes. Control effects: slow color change, quick color change, single color static. Waterproof and linkable for large commercial seasonal displays.",
        tag: "New",
        url: "#",
        image: "/RGBTwinkleRopeSync.webp",
      },
      {
        name: "String Light with Waterfall Effect",
        desc: "Green RGB string light on green wire with a flowing waterfall chase sequence. Produces a cascading colour effect ideal for tree installations and large outdoor seasonal displays.",
        tag: null,
        url: "#",
        image: "/WaterfallEffect.webp",
      },
      {
        name: "Digital RGB Soft Strip Light",
        desc: "Full-colour digital RGB soft LED strip light with individually addressable pixels for smooth colour-changing and colour-chasing sequences. Custom animation effects programmable as required. Flexible, cuttable clear PVC tubing on copper wire. Ideal for dynamic architectural, retail, and large-scale seasonal colour displays.",
        tag: "New",
        url: "#",
        image: "/RGBDigitalStrip.webp",
      },
      {
        name: "LED Snowfall 23mm",
        desc: "Cool white 23mm acrylic snowfall tubes with a cascading meteor-shower chase effect that mimics falling snow. Tapered tips and clear tubing on black wire, with multiple linkable tubes per set. Ideal for rooflines, eaves, and tree-mounted seasonal displays.",
        tag: "New",
        url: "#",
        image: "/SnowfallTube23mm.webp",
      },
      {
        name: "LED Snowfall 30mm",
        desc: "Cool white 30mm acrylic snowfall tube with the same cascading meteor-shower chase effect that mimics falling snow, in a larger diameter for higher output and visibility. Rigid clear tubing with daisy-chain connectors on both ends for linking multiple units. Ideal for rooflines, eaves, and tree-mounted seasonal displays.",
        tag: "New",
        url: "#",
        image: "/SnowfallTube30mm.webp",
      },
      {
        name: "Mini Meteor Light",
        desc: "Multicolor mini meteor tubes in green, blue, purple, red, amber, and white with a cascading chase effect that mimics shooting meteors. Slim compact profile, linkable for extended runs. Ideal for tree wrapping, garden borders, and vibrant seasonal displays.",
        tag: "New",
        url: "#",
        image: "/MiniMeteorLight.webp",
      },
    ],
  },
  {
    id: "lighting-structures",
    name: "Lighting Structures",
    description:
      "Free-standing motif sculptures and structural displays built around a steel frame for large-scale outdoor seasonal scenes.",
    seeAllUrl: "/gallery?category=lighting-structures",
    products: [
      {
        name: "Banff Polar Bear Light Sculpture",
        desc: "Part of the Banff Themed Series. Warm gold polar bear lighting structure with a deep blue scarf accent, built as a sparkling three-dimensional wildlife display for parks, plazas, winter festivals, and seasonal light trails.",
        tag: "Featured",
        url: "#",
        image: "/BanffPolarBear.webp",
      },
      {
        name: "Banff Mountain Goat Light Sculpture",
        desc: "Part of the Banff Themed Series. Cool white mountain goat lighting structure with warm gold horn accents, designed as a freestanding wildlife centrepiece for outdoor holiday installations and photo-friendly winter displays.",
        tag: null,
        url: "#",
        image: "/BanffMountainGoat.webp",
      },
      {
        name: "Banff Moose Light Sculpture",
        desc: "Part of the Banff Themed Series. Warm gold moose lighting structure with large illuminated antlers and a red scarf accent, ideal for Canadian-themed plazas, parks, resorts, and seasonal light trails.",
        tag: null,
        url: "#",
        image: "/BanffMoose.webp",
      },
      {
        name: "Banff Sea Turtle Light Sculpture",
        desc: "Part of the Banff Themed Series. Green and warm gold sea turtle lighting structure with a bright shell pattern and ground-stake supports, built for whimsical outdoor displays, gardens, parks, and festival routes.",
        tag: null,
        url: "#",
        image: "/BanffSeaTurtle.webp",
      },
      {
        name: "Banff Dolphin Light Sculpture",
        desc: "Part of the Banff Themed Series. Blue and cool white dolphin lighting structure mounted on a slim support pole, creating a bright jumping-dolphin scene for parks, waterfront displays, plazas, and seasonal attractions.",
        tag: null,
        url: "#",
        image: "/BanffDolphin.webp",
      },
      {
        name: "16 to 18ft Christmas Tree",
        desc: "Large-format 16–18 ft Christmas tree display, photographed at a provincial legislature rotunda. We supply both the tree structure and matching commercial-grade lights for a complete seasonal installation. Ideal for civic plazas, municipal buildings, and high-impact outdoor holiday displays.",
        tag: "Featured",
        url: "#",
        image: "/ChristmasTreeLegislature.webp",
      },
      {
        name: "Skiing Snowman Motif",
        desc: "Cool white LED snowman figure skiing with warm red boots and blue hat, scarf, and mitten accents. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5461-2DG, 160 x 117 cm.",
        tag: null,
        url: "#",
        image: "/SkiingSnowmanMotif.webp",
      },
      {
        name: "Skiing Santa Wave Motif",
        desc: "Warm red and white LED Santa figure skiing with a raised ski pole, warm gold skis, and a black belt buckle accent. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5462-2DG, 200 x 160 cm.",
        tag: null,
        url: "#",
        image: "/SkiingSantaWaveMotif.webp",
      },
      {
        name: "Waving Santa with Gift Sack Motif",
        desc: "Warm red and white LED Santa figure waving, with a warm gold gift sack slung over one shoulder. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5465-2DG, 200 x 150 cm.",
        tag: null,
        url: "#",
        image: "/WavingSantaGiftSackMotif.webp",
      },
      {
        name: "Skiing Reindeer Motif (Blue)",
        desc: "Warm gold LED reindeer figure skiing with cool blue scarf, mitten, and boot accents, and green skis. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5458-2DG, 200 x 140 cm.",
        tag: null,
        url: "#",
        image: "/SkiingReindeerBlueMotif.webp",
      },
      {
        name: "Skiing Reindeer Motif (Green)",
        desc: "Warm gold LED reindeer figure skiing with a cool green scarf, white belly accent, and red boots on green skis. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5459-2DG, 160 x 113 cm.",
        tag: null,
        url: "#",
        image: "/SkiingReindeerGreenMotif.webp",
      },
      {
        name: "Skiing Reindeer Motif (Red)",
        desc: "Warm gold LED reindeer figure skiing with warm red scarf, mitten, and boot accents on green skis. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5460-2DG, 190 x 107 cm.",
        tag: null,
        url: "#",
        image: "/SkiingReindeerRedMotif.webp",
      },
      {
        name: "Snowboarding Santa Motif",
        desc: "Warm red and white LED Santa figure snowboarding with cool blue goggles and a warm gold belt buckle accent, on a green snowboard. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5467-2DG, 120 x 90 cm.",
        tag: null,
        url: "#",
        image: "/SnowboardingSantaMotif.webp",
      },
      {
        name: "Golfing Santa Motif",
        desc: "Warm red and white LED Santa figure golfing in shorts with cool blue sunglasses, a warm gold golf club, and a wrapped gift box beside him. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5466-2DG, 140 x 120 cm.",
        tag: null,
        url: "#",
        image: "/GolfingSantaMotif.webp",
      },
      {
        name: "Santa & Reindeer Wave Motif",
        desc: "Warm red and white LED Santa figure waving alongside a warm gold LED reindeer, both with raised arms. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5464-2DG, 200 x 184 cm.",
        tag: "Featured",
        url: "#",
        image: "/SantaReindeerWaveMotif.webp",
      },
      {
        name: "Santa & Snowman Motif",
        desc: "Warm red and white LED Santa figure standing alongside a cool white LED snowman with a cool blue top hat and scarf. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5463-2DG, 200 x 170 cm.",
        tag: null,
        url: "#",
        image: "/SantaSnowmanMotif.webp",
      },
      {
        name: "Waving Santa Motif",
        desc: "Warm red and white LED Santa figure standing with one hand raised in a wave and the other on his hip. Sparkling rope-light fill over a durable steel frame. Ideal for lawns, plazas, and large-scale outdoor seasonal scenes. Model MF5466-2DG, 200 x 130 cm.",
        tag: null,
        url: "#",
        image: "/WavingSantaMotif.webp",
      },
      {
        name: "Christmas Tree with Star Motif",
        desc: "Warm gold LED Christmas tree with a red LED star topper and red LED ornament accents. Freestanding steel-frame structure for plazas and civic centrepieces. Model MF5628-2DG, 200 x 145 cm.",
        tag: null,
        url: "#",
        image: "/ChristmasTreeStarMotif.webp",
      },
      {
        name: "Wreath Photo-Op Motif",
        desc: "Walk-in warm gold and green LED wreath with a sparkling red LED bow and ornament accents, built around a bench seat for a festive photo opportunity. Model MF5629-3DG, (W)200 x (D)35 x (H)216 cm.",
        tag: null,
        url: "#",
        image: "/WreathPhotoOpMotif.webp",
      },
      {
        name: "Leaping Reindeer Pair Motif",
        desc: "Two warm gold LED reindeer in a leaping pose with sparkling red LED scarves, mounted on slim support poles. Freestanding steel-frame structures for plazas and lawns. Model MF5476-3DG, (W)147 x (D)40 x (H)190 cm.",
        tag: null,
        url: "#",
        image: "/LeapingReindeerPairMotif.webp",
      },
      {
        name: "Santa Sleigh Photo-Op Motif",
        desc: "Warm gold and red LED ornamental sleigh with scrollwork runners, sized for guests to sit inside for a festive photo opportunity. Model MF5630-3DG, (W)230 x (D)100 x (H)122 cm.",
        tag: null,
        url: "#",
        image: "/SantaSleighPhotoOpMotif.webp",
      },
      {
        name: "Skiing Santa Motif",
        desc: "Multicolor LED Santa figure in a dynamic skiing pose, with green LED skis and a white LED ski pole. Ideal for parks, plazas, and retail seasonal installations. Model MF5605-2DG, 130 x 100 cm.",
        tag: null,
        url: "#",
        image: "/SkiingSantaMotif.webp",
      },
      {
        name: "Gingerbread Man Motif",
        desc: "Warm gold LED gingerbread figure with a red and white Santa hat, candy cane accents, and a red bow tie. Ideal for parks, plazas, and retail seasonal installations. Model MF5606-2DG, 180 x 115 cm.",
        tag: null,
        url: "#",
        image: "/GingerbreadManMotif.webp",
      },
      {
        name: "Penguin Motif",
        desc: "Cool blue and white LED penguin figure with a red Santa hat and scarf and warm gold beak and feet. Ideal for parks, plazas, and retail seasonal installations. Model MF5609-2DG, 130 x 100 cm.",
        tag: null,
        url: "#",
        image: "/PenguinMotif.webp",
      },
      {
        name: "Penguin with Snowflakes Motif",
        desc: "Cool blue and white LED penguin figure with a red Santa hat and scarf and warm gold beak and feet, surrounded by warm gold and cool white LED snowflakes. Ideal for parks, plazas, and retail seasonal installations. Model MF5606-2DG, 180 x 130 cm.",
        tag: null,
        url: "#",
        image: "/PenguinSnowflakesMotif.webp",
      },
      {
        name: "Santa Sleigh & Reindeer Motif",
        desc: "Warm gold LED sleigh and reindeer pair with a red and white LED Santa figure and green and red holly accents. Ideal for parks, plazas, and retail seasonal installations. Model MF5607-2DG, 350 x 125 cm.",
        tag: null,
        url: "#",
        image: "/SantaSleighReindeerMotif.webp",
      },
      {
        name: "Gift Box Walk-Through Motif",
        desc: "Walk-through warm gold LED gift box structure with a sparkling red LED ribbon and bow, sized for guests to walk inside for a festive photo opportunity. Model MF5626-3DG, (W)285 x (D)271 x (H)340 cm.",
        tag: "Featured",
        url: "#",
        image: "/GiftBoxWalkThroughMotif.webp",
      },
      {
        name: "Antler Archway Motif",
        desc: "Walk-through warm gold LED reindeer-antler archway with a sparkling star topper and green and red holly accents, sized for guests to walk through for a festive photo opportunity. Model MF5627-3DG, (W)360 x (D)40 x (H)345 cm.",
        tag: null,
        url: "#",
        image: "/AntlerArchwayMotif.webp",
      },
      {
        name: "Ribbon-Bow Gift Box Archway",
        desc: "Walk-through warm gold LED gift box archway with a sparkling red LED ribbon and looped bow overhead, framed by tall gold pixel-fill panel legs. Sized for guests to walk through and pose inside. Model MF5498-3DG, (W)300 x (D)180 x (H)275 cm.",
        tag: null,
        url: "#",
        image: "/RibbonBowGiftBoxArchway.webp",
      },
      {
        name: "Starry Ornament Bench Archway",
        desc: "Walk-in warm gold LED ornament archway with cool-white LED star accents, built around a cushioned bench seat for a festive photo opportunity, topped with a hanging bauble loop accent. Model MF5499-3DG, (W)212 x (D)100 x (H)200 cm.",
        tag: null,
        url: "#",
        image: "/StarryOrnamentBenchArchway.webp",
      },
      {
        name: "Scroll Ornament Motif",
        desc: "Warm gold LED ornament bauble with an intricate cool-white LED scroll motif and a sparkling gold LED bow, designed to hang from an overhead cable or bracket. A refined accent for storefronts and pedestrian streets. Model MF5655-2DH, 85 x 65 cm.",
        tag: null,
        url: "#",
        image: "/ScrollOrnamentMotif.webp",
      },
      {
        name: "Star Ornament Archway Motif",
        desc: "Walk-through warm gold LED ornament archway with cool-white LED star accents, topped with a hanging warm gold and white LED bauble loop. Freestanding steel-frame structure sized for guests to walk through and pose inside. Model MF5501-3DG, (W)283 x (D)133 x (H)260 cm.",
        tag: null,
        url: "#",
        image: "/StarOrnamentArchwayMotif.webp",
      },
      {
        name: "Gift Box Bench Archway",
        desc: "Warm gold LED gift box archway with a sparkling red LED ribbon and looped bow overhead, built around a bench seat for a festive photo opportunity. Model MF5500-3DG, (W)233 x (D)60 x (H)215 cm.",
        tag: null,
        url: "#",
        image: "/GiftBoxBenchArchway.webp",
      },
      {
        name: "Heart Scroll Ornament Motif",
        desc: "Warm gold LED ornament bauble with a cool-white LED heart-clover scroll motif and a sparkling gold LED bow, designed to hang from an overhead cable or bracket. A refined accent for storefronts and pedestrian streets. Model MF5656-2DH, 85 x 65 cm.",
        tag: null,
        url: "#",
        image: "/HeartScrollOrnamentMotif.webp",
      },
      {
        name: "Teddy Bear Archway Motif",
        desc: "Sparkling warm gold LED teddy bear archway with a raised waving paw, wearing a red and white LED Santa hat and a red LED scarf, with cool-white LED paw-pad and ear accents. Walk-through steel-frame structure sized for guests to pose beneath. Model MF5645-3DG, (W)340 x (D)60 x (H)440 cm.",
        tag: null,
        url: "#",
        image: "/TeddyBearArchwayMotif.webp",
      },
      {
        name: "Hanging Gift Box Motif",
        desc: "Warm gold LED gift box outline with a sparkling red LED ribbon and heart-shaped bow loops, designed to hang from an overhead cable or bracket. A compact, eye-catching accent for storefronts and pedestrian streets. Model MF5641-2DH, 60 x 55 cm.",
        tag: null,
        url: "#",
        image: "/HangingGiftBoxMotif.webp",
      },
      {
        name: "Santa Hat Gnome Motif",
        desc: "Tall cone-shaped warm gold LED gnome figure topped with a sparkling red and white LED Santa hat, finished with a cool-white LED beard and pom-pom accent. Freestanding steel-frame structure for storefronts, plazas, and seasonal walkways. Model MF5646-3DG, (W)110 x (D)115 x (H)200 cm.",
        tag: null,
        url: "#",
        image: "/SantaHatGnomeMotif.webp",
      },
      {
        name: "Christmas Stocking Motif",
        desc: "Warm red LED rope-light stocking outline with a scrolled white cuff, a cool-white LED star accent at the toe, a warm gold candy cane hook, and a sparkling green LED Christmas tree rising from the cuff. Mounted on slim ground stakes for storefronts, streetscapes, and plaza displays. Model MF5639-2DH, 70 x 43 cm.",
        tag: null,
        url: "#",
        image: "/StockingMotif.webp",
      },
      {
        name: "Jingle Bells Motif",
        desc: "Two warm gold LED bells with cool-white pixel-fill fronts and a sparkling red LED bow, designed to hang from an overhead cable or bracket. A classic accent for storefronts, streetlamps, and pedestrian streets. Model MF5640-2DH, 70 x 54 cm.",
        tag: null,
        url: "#",
        image: "/JingleBellsMotif.webp",
      },
      {
        name: "Santa Cap Photo-Op Arch",
        desc: "Walk-through warm gold LED ring archway topped with a sparkling red and white LED Santa hat and pom-pom accent, sized for guests to stand inside for a festive photo opportunity. Model MF5644-3DG, (W)365 x (D)40 x (H)315 cm.",
        tag: null,
        url: "#",
        image: "/SantaCapArchMotif.webp",
      },
      {
        name: "Wrapped Gift Box Motif",
        desc: "Warm gold LED pixel-fill gift box with a sparkling red LED ribbon and looped bow on top. Freestanding steel-frame structure for storefronts, plazas, and seasonal walkways. Model MF5642-3DG, (W)174 x (D)30 x (H)160 cm.",
        tag: null,
        url: "#",
        image: "/GiftBoxMotif.webp",
      },
      {
        name: "Grand Wrapped Gift Box Motif",
        desc: "Large-format warm gold LED pixel-fill gift box with a sparkling red LED ribbon and looped bow on top. Freestanding steel-frame structure for storefronts, plazas, and seasonal walkways. Model MF5643-3DG, (W)174 x (D)30 x (H)210 cm.",
        tag: null,
        url: "#",
        image: "/GrandGiftBoxMotif.webp",
      },
      {
        name: "Silver Swirl Tree Motif",
        desc: "Sparkling cool-white LED swirl-branch Christmas tree with scattered warm gold LED star accents and a star topper. Freestanding steel-frame structure for plazas and storefronts. Model MF5669-2DG, 200 x 145 cm.",
        tag: null,
        url: "#",
        image: "/SilverSwirlTreeMotif.webp",
      },
      {
        name: "Snowflake Pine Tree Motif",
        desc: "Large-format warm gold LED Christmas tree with a tiered pine-bough silhouette and an interior cool-white LED snowflake motif, set on a wide circular base. Ideal for plazas, malls, and civic centrepieces. Model MF5572-3DG, (W)230 x (D)230 x (H)280 cm.",
        tag: null,
        url: "#",
        image: "/SnowflakePineTreeMotif.webp",
      },
      {
        name: "Red Star Swirl Tree Motif",
        desc: "Sparkling warm gold LED swirl-branch Christmas tree with scattered red LED star accents and a red star topper. Freestanding steel-frame structure for plazas and storefronts. Model MF5669-2DG, 200 x 145 cm (red-star colourway).",
        tag: null,
        url: "#",
        image: "/RedStarSwirlTreeMotif.webp",
      },
      {
        name: "Snowflake Ornament Pendant Motif",
        desc: "Warm gold LED ornament bauble with a cool-white LED starburst snowflake medallion and a sparkling gold LED bow, designed to hang from an overhead cable or bracket. A refined accent for storefronts and pedestrian streets. Model MF5672-2DH, 85 x 65 cm.",
        tag: null,
        url: "#",
        image: "/SnowflakeOrnamentPendantMotif.webp",
      },
      {
        name: "Truss Archway with Ornament Motif",
        desc: "Walk-through warm gold LED truss-style archway topped with a hanging ornament-box accent and loop hanger. Freestanding steel-frame structure sized for guests to walk through and pose beneath. Model MF5673-3DG, (W)340 x (D)40 x (H)310 cm.",
        tag: null,
        url: "#",
        image: "/TrussArchwayOrnamentMotif.webp",
      },
      {
        name: "Stacked Star Tree Motif",
        desc: "Tiered Christmas tree built from cascading warm gold and cool-white LED star frames in graduated sizes, finished with sparkling red LED ornament ball accents. Freestanding steel-frame structure for plazas and storefronts. Model MF5674-2DG, 250 x 178 cm.",
        tag: null,
        url: "#",
        image: "/StackedStarTreeMotif.webp",
      },
      {
        name: "Rainbow Lotus Flower Motif",
        desc: "Full-colour RGB LED lotus flower sculpture with layered petal fronds transitioning from green through blue and violet to pink, mounted on a round base plate. Freestanding steel-frame structure for plazas and civic centrepieces. Model MF5678-3DG-RGB, (W)200 x (D)200 x (H)200 cm.",
        tag: "Featured",
        url: "#",
        image: "/RainbowLotusFlowerMotif.webp",
      },
      {
        name: "RGB Firework Pendant Motif",
        desc: "Full-colour RGB LED starburst pendant with radiating sparkler-style spokes around a bright white LED core, designed to hang from an overhead cable or bracket. A compact, eye-catching accent for storefronts and pedestrian streets. Model MF5679-2DH-RGB, 55 x 48 cm.",
        tag: null,
        url: "#",
        image: "/RGBFireworkPendantMotif.webp",
      },
      {
        name: "Grand RGB Firework Pendant Motif",
        desc: "Full-colour RGB LED starburst pendant with radiating sparkler-style spokes around a bright white LED core, in a larger format than the standard firework pendant. Designed to hang from an overhead cable or bracket. Model MF5680-2DH-RGB, 70 x 61 cm.",
        tag: null,
        url: "#",
        image: "/GrandRGBFireworkPendantMotif.webp",
      },
      {
        name: "Rainbow Shooting Star Arch",
        desc: "Full-colour RGB LED archway transitioning through the spectrum from pink to violet to gold, trailing cool-white LED flower accents down to a sparkling silver LED star at its base. Freestanding steel-frame structure for plazas and pedestrian streets. Model MF5505-3DG-RGB, (W)470 x (D)20 x (H)250 cm.",
        tag: null,
        url: "#",
        image: "/RainbowShootingStarArch.webp",
      },
      {
        name: "RGB Ornament Ball Archway",
        desc: "Full-colour RGB LED walk-through ornament ball with a patchwork harlequin pattern in pink, teal, and green, accented with cool-white LED snowflakes and a sparkling silver hanger loop. Freestanding steel-frame structure sized for guests to walk through and pose inside. Model MF5857-3DG-RGB, (W)348 x (D)310 x (H)370 cm.",
        tag: null,
        url: "#",
        image: "/RGBOrnamentBallArchway.webp",
      },
      {
        name: "RGB Diamond Tree Motif",
        desc: "Full-colour RGB LED Christmas tree built from faceted diamond-pattern tiers transitioning through the spectrum, topped with a sparkling cool-white LED star. Freestanding steel-frame structure with a circular base. Model MF5660-3DG-RGB, (W)180 x (D)180 x (H)300 cm.",
        tag: null,
        url: "#",
        image: "/RGBDiamondTreeMotif.webp",
      },
      {
        name: "Teddy Bear Heart Archway Motif",
        desc: "Warm gold LED teddy bear archway with a red LED bow and heart-shaped legs forming a walk-through arch, finished with a cool-white LED muzzle accent. Freestanding steel-frame structure sized for guests to walk through and pose beneath. Model MF5702-3DG, (W)370 x (D)50 x (H)440 cm.",
        tag: null,
        url: "#",
        image: "/TeddyBearHeartArchwayMotif.webp",
      },
      {
        name: "Hanging Heart Ornament Motif",
        desc: "Layered warm pink and red LED heart ornament, designed to hang from an overhead cable or bracket. A romantic accent for storefronts and pedestrian streets. Model MF5703-2DH, 70 x 65 cm.",
        tag: null,
        url: "#",
        image: "/HangingHeartOrnamentMotif.webp",
      },
      {
        name: "Heart Bench Archway Motif",
        desc: "Walk-in layered warm pink and red LED heart archway built around a bench seat for a romantic photo opportunity. Freestanding steel-frame structure on a circular base. Model MF5704-3DG, (W)220 x (D)40 x (H)190 cm.",
        tag: null,
        url: "#",
        image: "/HeartBenchArchwayMotif.webp",
      },
      {
        name: "Heart Bouquet Motif",
        desc: "Four sparkling LED hearts in varied sizes and shades of red and pink, mounted on crossed slender stems rising from a square base like a bouquet of light. Freestanding steel-frame structure for plazas and storefronts. Model MF5708-2DG, 130 x 250 cm.",
        tag: null,
        url: "#",
        image: "/HeartBouquetMotif.webp",
      },
      {
        name: "Double Heart Pendant Motif",
        desc: "Overlapping warm red LED hearts in two sizes, designed to hang from an overhead cable or bracket. A romantic accent for storefronts and pedestrian streets. Model MF5705-2DH, 70 x 70 cm.",
        tag: null,
        url: "#",
        image: "/DoubleHeartPendantMotif.webp",
      },
      {
        name: "LOVE Letter Sculpture",
        desc: "Large-format red and white LED LOVE letter sculpture with a heart-shaped O and sparkling heart accents on the L and E, built around integrated bench seating for a romantic photo opportunity. Freestanding steel-frame structure for plazas and event installations. Model MF5707-3DG, (W)617 x (D)60 x (H)190 cm.",
        tag: null,
        url: "#",
        image: "/LoveLetterSculpture.webp",
      },
      {
        name: "Heart-in-Heart Pendant Motif",
        desc: "Warm pink LED heart outline framing a solid red LED heart centre, designed to hang from an overhead cable or bracket. A romantic accent for storefronts and pedestrian streets. Model MF5706-2DH, 70 x 65 cm.",
        tag: null,
        url: "#",
        image: "/HeartInHeartPendantMotif.webp",
      },
      {
        name: "Illuminated Block Letters",
        desc: "Large-format warm white LED block letters on a ground-mounted base. Front-lit with edge-lit halo effect. Fully customizable lettering for airports, civic plazas, and high-profile seasonal installations.",
        tag: null,
        url: "#",
        image: "/IlluminatedLetters.webp",
      },
      {
        name: "Custom City Marquee Sign",
        desc: "Large-format custom city sign with pixel-fill dot matrix lettering, blue LED accent base, and integrated skyline silhouette. Designed for civic plazas, airports, and landmark installations. Fully bespoke — city name, colours, and skyline profile made to order.",
        tag: null,
        url: "#",
        image: "/CitySignMarquee.webp",
      },
      {
        name: "Snowflake Arch Motif",
        desc: "Warm gold LED arch formed by two curved uprights embedded with sparkling cool-white LED snowflakes of varying sizes, meeting near the top in a scrolled finial topped with a large cool-white LED snowflake burst. Freestanding steel-frame structure for plazas and pedestrian walkways. Model MF5666-3DG, (W)173 x (D)60 x (H)280 cm.",
        tag: "Featured",
        url: "#",
        image: "/SnowflakeArchMotif.webp",
      },
      {
        name: "Grand Snowflake Starburst Motif",
        desc: "Warm gold LED eight-point star frame centred on a bold cool-white LED snowflake medallion, mounted on a rectangular base. Freestanding steel-frame structure for plazas and storefronts. Model MF5667-3DG, (W)200 x (D)30 x (H)200 cm.",
        tag: null,
        url: "#",
        image: "/GrandSnowflakeStarburstMotif.webp",
      },
      {
        name: "Snowflake Starburst Motif",
        desc: "Warm gold LED eight-point star frame centred on a bold cool-white LED snowflake medallion, in a slightly narrower profile, mounted on a rectangular base. Freestanding steel-frame structure for plazas and storefronts. Model MF5668-3DG, (W)173 x (D)30 x (H)200 cm.",
        tag: null,
        url: "#",
        image: "/SnowflakeStarburstMotif.webp",
      },
      {
        name: "Jagged Star Snowflake Archway Motif",
        desc: "Warm gold LED zigzag star-shaped archway with sparkling cool-white LED snowflakes of varying sizes along the points, mounted on two square bases forming a walk-through star opening. Freestanding steel-frame structure for plazas and pedestrian walkways.",
        tag: null,
        url: "#",
        image: "/JaggedStarSnowflakeArchway.webp",
      },
      {
        name: "Tabletop Snowflake Star Motif",
        desc: "Warm gold LED five-point star frame centred on a bold cool-white LED snowflake medallion, mounted on a rectangular base. Freestanding steel-frame structure for plazas and storefronts.",
        tag: null,
        url: "#",
        image: "/TabletopSnowflakeStarMotif.webp",
      },
      {
        name: "Swirl-Trimmed Snowflake Tree Motif",
        desc: "Warm gold LED Christmas tree with tiered swirl-trimmed boughs, cool-white LED snowflake medallions at each tier, and a sparkling star finial. Freestanding steel-frame structure with a circular base. Ideal for plazas and civic centrepieces.",
        tag: null,
        url: "#",
        image: "/SwirlTrimmedSnowflakeTreeMotif.webp",
      },
    ],
  },
  {
    id: "city-letters",
    name: "City & Airport Letters",
    description:
      "Large-format illuminated letters and signage for high-visibility civic and terminal installations. Custom sizing available.",
    seeAllUrl: "/gallery?category=city-letters",
    products: [
      {
        name: "Illuminated Block Letters",
        desc: "Large-format warm white LED block letters on a ground-mounted base. Front-lit with edge-lit halo effect. Fully customizable lettering for airports, civic plazas, and high-profile seasonal installations.",
        tag: "Most Popular",
        url: "#",
        image: "/IlluminatedLetters.webp",
      },
      {
        name: "Custom City Marquee Sign",
        desc: "Large-format custom city sign with pixel-fill dot matrix lettering, blue LED accent base, and integrated skyline silhouette. Designed for civic plazas, airports, and landmark installations. Fully bespoke — city name, colours, and skyline profile made to order.",
        tag: "Custom",
        url: "#",
        image: "/CitySignMarquee.webp",
      },
      {
        name: "YYC Airport Letters",
        desc: "Large-format illuminated YYC letters in warm gold LED rope light — Calgary's airport code rendered as a landmark marquee. Ideal for terminal welcome zones, civic plazas, and photo moments. Fully customizable in size and colour.",
        tag: "New",
        url: "#",
        image: "/YYCAirportLetters.webp",
      },
      {
        name: "YXE Airport Letters",
        desc: "Large-format illuminated YXE letters in warm gold LED rope light — Saskatoon's airport code rendered as a landmark marquee. Ideal for terminal welcome zones, civic plazas, and photo moments. Fully customizable in size and colour.",
        tag: "New",
        url: "#",
        image: "/YXEAirportLetters.webp",
      },
    ],
  },
  {
    id: "accessories",
    name: "Connecting Accessories",
    description:
      "Everything needed to complete, extend, and protect your installation — from weatherproof connectors to heavy-duty timers.",
    seeAllUrl: "/gallery?category=accessories",
    products: [
      {
        name: "One Drive Two",
        desc: "Y-splitter connector that powers two string light runs from a single driver output. Weatherproof screw-lock connectors on all three ends. Simplifies wiring for large installations.",
        tag: "Essential",
        url: "#",
        image: "/OneDriveTwo.webp",
      },
      {
        name: "Y Shape LED Strip Light Extension Cord",
        desc: "Y-shaped extension cord splitting a single driver input into two output branches, terminated with quick-connect pin sockets and matching pin connectors. Simplifies wiring for branching one power source into two runs.",
        tag: "Essential",
        url: "#",
        image: "/YShapeExtensionCord.webp",
      },
      {
        name: "LED Strip Light Male Pin",
        desc: "White quick-connect male pin connector with two metal prongs on each side. Joins two LED strip light sections end-to-end without soldering. Tool-free connection for fast strip light installation and repairs.",
        tag: "Essential",
        url: "#",
        image: "/StripLightMalePin.webp",
      },
      {
        name: "One Drive Three",
        desc: "3-way splitter connector that powers three string light runs from a single driver output. Weatherproof screw-lock connectors on all four ends. Ideal for maximising coverage from one power source.",
        tag: "Essential",
        url: "#",
        image: "/OneDriveThree.webp",
      },
      {
        name: "One Drive Five",
        desc: "5-way splitter connector that powers five string light runs from a single driver output. Solid housing with weatherproof connectors. Built for large-scale municipal and commercial installations requiring maximum run coverage.",
        tag: "Essential",
        url: "#",
        image: "/OneDriveFive.webp",
      },
      {
        name: "Extension Cable",
        desc: "Weatherproof extension cable with screw-lock connectors on both ends. Bridges the gap between driver and string light runs. Compatible with all standard connector fittings in our range.",
        tag: "Essential",
        url: "#",
        image: "/ExtensionCable.webp",
      },
      {
        name: "LED Strip Light Extension Cable",
        desc: "White extension cable with clear quick-connect pin connectors on both ends, plus matching waterproof heat-shrink sleeves for a sealed outdoor splice. Bridges the gap between driver and LED strip light runs.",
        tag: "Essential",
        url: "#",
        image: "/StripLightExtensionCable.webp",
      },
      {
        name: "Curtain Main Cable",
        desc: "Multi-drop curtain main cable with multiple evenly-spaced screw-lock output connectors. Feeds several curtain light strands from a single input. Ideal for wide building facade installations.",
        tag: null,
        url: "#",
        image: "/CurtainMainCable2.webp",
      },
      {
        name: "Rope Light to Light Chain Connection Cable",
        desc: "Adapter cable with pin terminals for connecting rope light to a standard light chain. Includes clear sleeve housing and crimp pins. Enables seamless integration between rope and string light systems.",
        tag: null,
        url: "#",
        image: "/RopeToChainCable.webp",
      },
      {
        name: "T Connector — A",
        desc: "T-shaped 3-way connector for branching a single string light run into two outputs. Compact weatherproof housing with screw-lock ends. Simplifies layout for corner and intersection wiring.",
        tag: null,
        url: "#",
        image: "/TConnectorA.webp",
      },
      {
        name: "T Connector — B",
        desc: "T-shaped 3-way connector on white cable with screw-lock ends. Branches one input into two parallel outputs. Ideal for symmetric installations such as rooflines, archways, and pole-mounted runs.",
        tag: null,
        url: "#",
        image: "/TConnectorB.webp",
      },
      {
        name: "Power Cable",
        desc: "White power cable with Schuko plug and locking output connector. Connects your driver or power supply to a standard outlet. Suitable for indoor and covered outdoor power sources.",
        tag: null,
        url: "#",
        image: "/PowerCable.webp",
      },
      {
        name: "6A Detachable Rectifier",
        desc: "6A detachable rectifier with Schuko plug input and dual screw-lock output connectors. Converts AC mains to low-voltage DC for string light runs. Compact vented housing for reliable heat dissipation.",
        tag: null,
        url: "#",
        image: "/Rectifier6A.webp",
      },
      {
        name: "6A Rectifier",
        desc: "6A inline rectifier with Schuko plug and dual screw-lock output connectors on black cable. Converts AC mains to low-voltage DC. Compact vented housing — a reliable power solution for string light installations.",
        tag: null,
        url: "#",
        image: "/Rectifier6AStandard.webp",
      },
      {
        name: "LED Strip Light Power Cord Accessory Set",
        desc: "White Schuko-plug power cord with an inline rectifier driver and a quick-connect pin-terminated output for LED strip lights. Converts AC mains to low-voltage DC in an all-in-one power solution for strip light installations.",
        tag: null,
        url: "#",
        image: "/StripLightPowerCordSet.webp",
      },
    ],
  },
];

// Flat list of all products with their category attached — used by the gallery
export interface FlatProduct extends Product {
  categoryId: string;
  categoryName: string;
}

export const allProducts: FlatProduct[] = categories.flatMap((cat) =>
  cat.products.map((p) => ({
    ...p,
    categoryId: cat.id,
    categoryName: cat.name,
  }))
);
